# -*- mode: ruby -*-
# vi: set ft=ruby :

#box = "bento/ubuntu-20.04"
box = "ubuntu/focal64"

Vagrant.configure("2") do |config|
  config.vm.box = box

  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.define "image" do |web|
    web.vm.provision "shell", inline: <<-SHELL
      set -e
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y --no-install-recommends ansible git

      rm -rf isucon7q-ubuntu20
      git clone https://github.com/uta8a/isucon7q-ubuntu20
      (
        cd isucon7q-ubuntu20/infra/ansible/
        ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3 PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i local image.yml
      )
      rm -rf isucon7q-ubuntu20
    SHELL
  end

  config.vm.define "bench" do |bench|
    bench.vm.provision "shell", inline: <<-SHELL
      set -e
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y --no-install-recommends ansible git

      rm -rf isucon7q-ubuntu20
      git clone https://github.com/uta8a/isucon7q-ubuntu20
      (
        cd isucon7q-ubuntu20/infra/ansible/        
        ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3 PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i local bench.yml
      )
      rm -rf isucon7q-ubuntu20
    SHELL
  end
end

# ref. https://github.com/matsuu/vagrant-isucon/blob/master/isucon7-qualifier/Vagrantfile
