# -*- mode: ruby -*-
# vi: set ft=ruby :

#box = "bento/ubuntu-20.04"
box = "ubuntu/focal64"

Vagrant.configure("2") do |config|
  config.vm.box = box

  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.define "image" do |web|
    web.vm.provision "shell", inline: <<-SHELL
      set -e
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y --no-install-recommends ansible git

      rm -rf ansible-isucon
      git clone https://github.com/matsuu/ansible-isucon.git # 変更加える
      (
        cd ansible-isucon/isucon7-qualifier
	PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i local image.yml
      )
      rm -rf ansible-isucon
    SHELL
  end

  config.vm.define "bench" do |bench|
    bench.vm.provision "shell", inline: <<-SHELL
      set -e
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y --no-install-recommends ansible git

      rm -rf ansible-isucon
      git clone https://github.com/matsuu/ansible-isucon.git # 変更加える
      (
        cd ansible-isucon/isucon7-qualifier
        PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i local bench.yml
      )
      rm -rf ansible-isucon
    SHELL
  end
end

# ref. https://github.com/matsuu/vagrant-isucon/blob/master/isucon7-qualifier/Vagrantfile
