---

- name: Install mysql
  apt:
    state: present
    name: "{{item}}"
  loop:
    - make
    - mysql-server
    - python3-pip
    # - python-mysqldb

- name: Install PyMySQL
  pip:
    name: PyMySQL

- name: Install golang binary
  get_url:
    url: https://golang.org/dl/go1.15.6.linux-amd64.tar.gz
    validate_certs: no
    dest: /home/isucon/go.tar.gz
  args:
    creates: /home/isucon/local/go/bin/go
  become_user: isucon

- name: Install golang
  shell: |
    mkdir /home/isucon/local
    tar -C /home/isucon/local -xzf /home/isucon/go.tar.gz
  args:
    creates: /home/isucon/local/go/bin/go
  become_user: isucon

- name: Migration
  shell: |
    export PATH="$HOME/local/go/bin:$HOME/go/bin:$PATH"
    go get github.com/constabulary/gb/...
    cd /home/isucon/isubata/bench
    gb vendor restore
    make
    ./bin/gen-initial-dataset
  args:
    creates: /home/isucon/isubata/bench/isucon7q-initial-dataset.sql.gz
  become_user: isucon

- name: init.sh
  shell: "/home/isucon/isubata/db/init.sh"

- name: Create mysql user
  mysql_user:
    name: isucon
    password: isucon
    host: "%"
    priv: "*.*:ALL"
    state: present

- name: Dataset
  shell: "zcat /home/isucon/isubata/bench/isucon7q-initial-dataset.sql.gz | mysql --default-character-set=utf8 --max_allowed_packet=512M isubata"

- name: file
  file:
    path: /home/isucon/isubata/bench/isucon7q-initial-dataset.sql.gz
    state: absent

- name: copy
  copy:
    src: /home/isucon/isubata/files/db/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/
    remote_src: yes
  notify: restart mysql

- name: Start mysql service
  service:
    name: mysql
    enabled: yes
    state: started
